### ISSUE TITLE
Emit fixed, but DLL's not updated

### ISSUE THREAD

**Issue by Nonameghost** [NetEase/UnitySocketIO#20] opened 2013-12-16 03:29 UTC
Hey there!

Thanks for making this interesting library. I've noticed you solved the "emit" problem, but the libraries have not been rebuilt. It worked just fine when I re-built them, but the current "bin/debug" is outdated.

Just putting this here in case anybody still has issues with emit. If someone can update the repo, that would probably help a few users (The ones who don't feel comfortable building them) with their problems.

Thanks!
(I'd update them myself but I figure one of the authors doing it is faster than a pull request.)

**Comment by squaretone** [comment] 2014-04-22 20:20
I'm running into the emit issue which I'm guessing is caused by the outdated DLLs. What do you typically use to build them?

**Comment by tomASTI** [comment] 2014-06-04 11:14
Hello,

Not sure if this was merged in properly, I've got the latest revision but still having the same problem...

**Closed as completed** 2017-08-22 16:28 UTC
